
/**
* RandomOutOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RandomOut.idl
* 4 апреля 2023 г. 23:25:20 MSK
*/

public interface RandomOutOperations 
{
  void addWords (String word);
  String getLetters (String res);
} // interface RandomOutOperations
