
/**
* RandomOutHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RandomOut.idl
* 4 апреля 2023 г. 23:25:20 MSK
*/

public final class RandomOutHolder implements org.omg.CORBA.portable.Streamable
{
  public RandomOut value = null;

  public RandomOutHolder ()
  {
  }

  public RandomOutHolder (RandomOut initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RandomOutHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RandomOutHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RandomOutHelper.type ();
  }

}
